language: python

sudo: false

python:
  - "3.6.2"
  - "3.7.7"
  - "3.8.2"

install:
  - python setup.py install

script:
  - py.test --cov=timefhuman

after_success:
  - CI=true TRAVIS=true coveralls
